// Code generated by fqlmeta. DO NOT EDIT.
// Generated at: 2026-08-21T14:33:19Z

name: "cloudregistration"

entities: {
	settings: {
		fql_properties: {
			dspm_host_account_id: {type: "string", filterable: true}
			vulnerability_scanning_host_account_id: {type: "string", filterable: true}
		}
	}
}
