// Code generated by fqlmeta. DO NOT EDIT.
// Generated at: 2026-08-21T14:25:03Z

name: "cspm"

entities: {
	rule: {
		fql_properties: {
		}
	}

	compliance_control: {
		fql_properties: {
			account_id: {type: "string", filterable: true}
			account_name: {type: "string", filterable: true}
			benchmark_name: {type: "string", filterable: true}
			benchmark_version: {type: "string", filterable: true}
			cloud_provider: {type: "string", filterable: true}
			compliant: {type: "string", filterable: true}
			framework: {type: "string", filterable: true}
			region: {type: "string", filterable: true}
			requirement: {type: "string", filterable: true}
			resource_type: {type: "string", filterable: true}
			resource_type_name: {type: "string", filterable: true}
			section: {type: "string", filterable: true}
			service: {type: "string", filterable: true}
			service_category: {type: "string", filterable: true}
		}
	}

	compliance_framework: {
		fql_properties: {
		}
	}

	aspm: {
		fql_properties: {
			FQLAssetCloudScope: {type: "string", filterable: true}
			account_bitmap_token_64: {type: "string", filterable: true}
			account_id: {type: "string", filterable: true}
			account_name: {type: "string", filterable: true}
			active: {type: "string", filterable: true}
			application_name: {type: "string", filterable: true}
			aspm.cloud_account: {type: "string", filterable: true}
			aspm.cloud_region: {type: "string", filterable: true}
			aspm.deployment_cloud_resource_id: {type: "string", filterable: true}
			aspm.deployment_provider: {type: "string", filterable: true}
			aspm.deployment_type: {type: "string", filterable: true}
			aspm.technologies: {type: "string", filterable: true}
			business_context.contributing_rule_ids: {type: "string", filterable: true}
			business_context.criticality: {type: "string", filterable: true}
			business_context.evaluated_at: {type: "string", filterable: true}
			business_impact: {type: "string", filterable: true}
			cloud_provider: {type: "string", filterable: true}
			cloud_risks.rule: {type: "string", filterable: true}
			cloud_risks.severity: {type: "string", filterable: true}
			cloud_risks.status: {type: "string", filterable: true}
			cloud_scope: {type: "string", filterable: true}
			compliant.benchmark_name: {type: "string", filterable: true}
			compliant.benchmark_version: {type: "string", filterable: true}
			compliant.framework: {type: "string", filterable: true}
			compliant.policy_id: {type: "string", filterable: true}
			compliant.requirement: {type: "string", filterable: true}
			compliant.rule: {type: "string", filterable: true}
			compliant.section: {type: "string", filterable: true}
			control.benchmark.name: {type: "string", filterable: true}
			control.benchmark.version: {type: "string", filterable: true}
			control.framework: {type: "string", filterable: true}
			control.requirement: {type: "string", filterable: true}
			control.type: {type: "string", filterable: true}
			control.version: {type: "string", filterable: true}
			creation_time: {type: "string", filterable: true}
			cve_ids: {type: "string", filterable: true}
			data_classifications.found: {type: "string", filterable: true}
			data_classifications.label: {type: "string", filterable: true}
			data_classifications.label_id: {type: "string", filterable: true}
			data_classifications.scanned: {type: "string", filterable: true}
			data_classifications.tag: {type: "string", filterable: true}
			data_classifications.tag_id: {type: "string", filterable: true}
			environment: {type: "string", filterable: true}
			exprt_ratings: {type: "string", filterable: true}
			first_seen: {type: "string", filterable: true}
			highest_severity: {type: "string", filterable: true}
			id: {type: "string", filterable: true}
			insights.boolean_value: {type: "string", filterable: true}
			insights.date_value: {type: "string", filterable: true}
			insights.id: {type: "string", filterable: true}
			insights.integer_value: {type: "string", filterable: true}
			insights.string_list_value: {type: "string", filterable: true}
			insights.string_value: {type: "string", filterable: true}
			instance_id: {type: "string", filterable: true}
			instance_state: {type: "string", filterable: true}
			ioa_count: {type: "string", filterable: true}
			iom_count: {type: "string", filterable: true}
			legacy_resource_id: {type: "string", filterable: true}
			legacy_uuid: {type: "string", filterable: true}
			managed_by: {type: "string", filterable: true}
			non_compliant.benchmark_name: {type: "string", filterable: true}
			non_compliant.benchmark_version: {type: "string", filterable: true}
			non_compliant.framework: {type: "string", filterable: true}
			non_compliant.policy_id: {type: "string", filterable: true}
			non_compliant.requirement: {type: "string", filterable: true}
			non_compliant.rule: {type: "string", filterable: true}
			non_compliant.rule_name: {type: "string", filterable: true}
			non_compliant.section: {type: "string", filterable: true}
			non_compliant.severity: {type: "string", filterable: true}
			organization_Id: {type: "string", filterable: true}
			os_version: {type: "string", filterable: true}
			platform_name: {type: "string", filterable: true}
			publicly_exposed: {type: "string", filterable: true}
			region: {type: "string", filterable: true}
			resource_gcrn: {type: "string", filterable: true}
			resource_id: {type: "string", filterable: true}
			resource_name: {type: "string", filterable: true}
			resource_parent: {type: "string", filterable: true}
			resource_type: {type: "string", filterable: true}
			resource_type_name: {type: "string", filterable: true}
			sensor_priority: {type: "string", filterable: true}
			service: {type: "string", filterable: true}
			service_category: {type: "string", filterable: true}
			severity: {type: "string", filterable: true}
			snapshot_detections: {type: "string", filterable: true}
			ssm_managed: {type: "string", filterable: true}
			status: {type: "string", filterable: true}
			tag_key: {type: "string", filterable: true}
			tag_value: {type: "string", filterable: true}
			tags: {type: "string", filterable: true}
			tags_string: {type: "string", filterable: true}
			tenant_id: {type: "string", filterable: true}
			updated_at: {type: "string", filterable: true}
			zone: {type: "string", filterable: true}
		}
	}

	vmware: {
		fql_properties: {
			cluster_id: {type: "string", filterable: true}
			cluster_name: {type: "string", filterable: true}
			vmware.guest_os_id: {type: "string", filterable: true}
			vmware.guest_os_version: {type: "string", filterable: true}
			vmware.host_system_name: {type: "string", filterable: true}
			vmware.host_type: {type: "string", filterable: true}
			vmware.instance_uuid: {type: "string", filterable: true}
			vmware.vm_host_name: {type: "string", filterable: true}
			vmware.vm_tools_status: {type: "string", filterable: true, enum: ["enabled", "disabled"]}
		}
	}

	asset: {
		fql_properties: {
			FQLAssetCloudScope: {type: "string", filterable: true}
			account_bitmap_token_64: {type: "string", filterable: true}
			account_id: {type: "string", filterable: true}
			account_name: {type: "string", filterable: true}
			active: {type: "string", filterable: true}
			application_name: {type: "string", filterable: true}
			aspm.cloud_account: {type: "string", filterable: true}
			aspm.cloud_region: {type: "string", filterable: true}
			aspm.deployment_cloud_resource_id: {type: "string", filterable: true}
			aspm.deployment_provider: {type: "string", filterable: true}
			aspm.deployment_type: {type: "string", filterable: true}
			aspm.technologies: {type: "string", filterable: true}
			azure.resource_group: {type: "string", filterable: true}
			azure.vm_id: {type: "string", filterable: true}
			business_context.contributing_rule_ids: {type: "string", filterable: true}
			business_context.criticality: {type: "string", filterable: true}
			business_context.evaluated_at: {type: "string", filterable: true}
			business_impact: {type: "string", filterable: true}
			cid: {type: "string", filterable: true}
			cloud_provider: {type: "string", filterable: true}
			cloud_risks.rule: {type: "string", filterable: true}
			cloud_risks.severity: {type: "string", filterable: true}
			cloud_risks.status: {type: "string", filterable: true}
			cloud_scope: {type: "string", filterable: true}
			cluster_id: {type: "string", filterable: true}
			cluster_name: {type: "string", filterable: true}
			compartment_ocid: {type: "string", filterable: true}
			compliant.benchmark_name: {type: "string", filterable: true}
			compliant.benchmark_version: {type: "string", filterable: true}
			compliant.framework: {type: "string", filterable: true}
			compliant.policy_id: {type: "string", filterable: true}
			compliant.requirement: {type: "string", filterable: true}
			compliant.rule: {type: "string", filterable: true}
			compliant.section: {type: "string", filterable: true}
			configuration.id: {type: "string", filterable: true}
			control.benchmark.name: {type: "string", filterable: true}
			control.benchmark.version: {type: "string", filterable: true}
			control.framework: {type: "string", filterable: true}
			control.requirement: {type: "string", filterable: true}
			control.type: {type: "string", filterable: true}
			control.version: {type: "string", filterable: true}
			creation_time: {type: "string", filterable: true}
			cve_ids: {type: "string", filterable: true}
			data_classifications.found: {type: "string", filterable: true}
			data_classifications.label: {type: "string", filterable: true}
			data_classifications.label_id: {type: "string", filterable: true}
			data_classifications.scanned: {type: "string", filterable: true}
			data_classifications.tag: {type: "string", filterable: true}
			data_classifications.tag_id: {type: "string", filterable: true}
			data_classifications.timestamp: {type: "string", filterable: true}
			environment: {type: "string", filterable: true}
			exprt_ratings: {type: "string", filterable: true}
			first_seen: {type: "string", filterable: true}
			gcp.multi_region: {type: "string", filterable: true}
			gcp.physical_region: {type: "string", filterable: true}
			highest_severity: {type: "string", filterable: true}
			id: {type: "string", filterable: true}
			insights.boolean_value: {type: "string", filterable: true}
			insights.date_value: {type: "string", filterable: true}
			insights.id: {type: "string", filterable: true}
			insights.integer_value: {type: "string", filterable: true}
			insights.string_list_value: {type: "string", filterable: true}
			insights.string_value: {type: "string", filterable: true}
			instance_id: {type: "string", filterable: true}
			instance_state: {type: "string", filterable: true}
			ioa_count: {type: "string", filterable: true}
			iom_count: {type: "string", filterable: true}
			legacy_resource_id: {type: "string", filterable: true}
			legacy_uuid: {type: "string", filterable: true}
			managed_by: {type: "string", filterable: true}
			non_compliant.benchmark_name: {type: "string", filterable: true}
			non_compliant.benchmark_version: {type: "string", filterable: true}
			non_compliant.framework: {type: "string", filterable: true}
			non_compliant.policy_id: {type: "string", filterable: true}
			non_compliant.requirement: {type: "string", filterable: true}
			non_compliant.rule: {type: "string", filterable: true}
			non_compliant.rule_name: {type: "string", filterable: true}
			non_compliant.section: {type: "string", filterable: true}
			non_compliant.severity: {type: "string", filterable: true}
			organization_Id: {type: "string", filterable: true}
			os_version: {type: "string", filterable: true}
			platform_name: {type: "string", filterable: true}
			publicly_exposed: {type: "string", filterable: true}
			region: {type: "string", filterable: true}
			resource_gcrn: {type: "string", filterable: true}
			resource_id: {type: "string", filterable: true}
			resource_name: {type: "string", filterable: true}
			resource_parent: {type: "string", filterable: true}
			resource_type: {type: "string", filterable: true}
			resource_type_name: {type: "string", filterable: true}
			sensor_priority: {type: "string", filterable: true}
			service: {type: "string", filterable: true}
			service_category: {type: "string", filterable: true}
			severity: {type: "string", filterable: true}
			snapshot_detections: {type: "string", filterable: true}
			ssm_managed: {type: "string", filterable: true}
			status: {type: "string", filterable: true}
			tag_key: {type: "string", filterable: true}
			tag_value: {type: "string", filterable: true}
			tags: {type: "string", filterable: true}
			tags_string: {type: "string", filterable: true}
			tenant_id: {type: "string", filterable: true}
			updated_at: {type: "string", filterable: true}
			vmware.guest_os_id: {type: "string", filterable: true}
			vmware.guest_os_version: {type: "string", filterable: true}
			vmware.host_name: {type: "string", filterable: true}
			vmware.host_system_name: {type: "string", filterable: true}
			vmware.host_type: {type: "string", filterable: true}
			vmware.instance_uuid: {type: "string", filterable: true}
			vmware.vm_host_name: {type: "string", filterable: true}
			vmware.vm_tools_status: {type: "string", filterable: true, enum: ["enabled", "disabled"]}
			zone: {type: "string", filterable: true}
		}
	}

	global_filters_aggregate: {
		fql_properties: {
			account_bitmap_token_64: {type: "string", filterable: true}
			account_id: {type: "string", filterable: true}
			account_name: {type: "string", filterable: true}
			application_name: {type: "string", filterable: true}
			aspm.cloud_account: {type: "string", filterable: true}
			aspm.cloud_region: {type: "string", filterable: true}
			aspm.deployment_provider: {type: "string", filterable: true}
			aspm.deployment_type: {type: "string", filterable: true}
			azure.resource_group: {type: "string", filterable: true}
			business_context.contributing_rule_ids: {type: "string", filterable: true}
			business_context.criticality: {type: "string", filterable: true}
			business_context.evaluated_at: {type: "string", filterable: true}
			cloud_provider: {type: "string", filterable: true}
			cloud_risks.rule: {type: "string", filterable: true}
			cloud_risks.severity: {type: "string", filterable: true}
			cloud_risks.status: {type: "string", filterable: true}
			cluster_id: {type: "string", filterable: true}
			cluster_name: {type: "string", filterable: true}
			compartment_ocid: {type: "string", filterable: true}
			control.benchmark.name: {type: "string", filterable: true}
			control.benchmark.version: {type: "string", filterable: true}
			control.framework: {type: "string", filterable: true}
			control.type: {type: "string", filterable: true}
			control.version: {type: "string", filterable: true}
			creation_time: {type: "string", filterable: true}
			cve.id: {type: "string", filterable: true}
			data_classifications.found: {type: "string", filterable: true}
			data_classifications.label: {type: "string", filterable: true}
			data_classifications.label_id: {type: "string", filterable: true}
			data_classifications.scanned: {type: "string", filterable: true}
			data_classifications.tag: {type: "string", filterable: true}
			data_classifications.tag_id: {type: "string", filterable: true}
			exprt_ratings: {type: "string", filterable: true}
			first_seen: {type: "string", filterable: true}
			groups: {type: "string", filterable: true}
			groups.business_impact: {type: "string", filterable: true}
			groups.business_unit: {type: "string", filterable: true}
			highest_severity: {type: "string", filterable: true}
			insights.boolean_value: {type: "string", filterable: true}
			insights.date_value: {type: "string", filterable: true}
			insights.id: {type: "string", filterable: true}
			insights.integer_value: {type: "string", filterable: true}
			insights.string_list_value: {type: "string", filterable: true}
			insights.string_value: {type: "string", filterable: true}
			instance_state: {type: "string", filterable: true}
			ioa_count: {type: "string", filterable: true}
			iom_count: {type: "string", filterable: true}
			managed_by: {type: "string", filterable: true}
			non_compliant.benchmark_name: {type: "string", filterable: true}
			non_compliant.benchmark_version: {type: "string", filterable: true}
			non_compliant.framework: {type: "string", filterable: true}
			non_compliant.requirement: {type: "string", filterable: true}
			non_compliant.rule: {type: "string", filterable: true}
			non_compliant.rule_id: {type: "string", filterable: true}
			non_compliant.rule_name: {type: "string", filterable: true}
			non_compliant.section: {type: "string", filterable: true}
			platform_name: {type: "string", filterable: true}
			publicly_exposed: {type: "string", filterable: true}
			region: {type: "string", filterable: true}
			resource_gcrn: {type: "string", filterable: true}
			resource_id: {type: "string", filterable: true}
			resource_name: {type: "string", filterable: true}
			resource_parent: {type: "string", filterable: true}
			resource_type: {type: "string", filterable: true}
			resource_type_name: {type: "string", filterable: true}
			sensor_priority: {type: "string", filterable: true}
			service: {type: "string", filterable: true}
			service_category: {type: "string", filterable: true}
			severity: {type: "string", filterable: true}
			snapshot_detections: {type: "string", filterable: true}
			status: {type: "string", filterable: true}
			tag_key: {type: "string", filterable: true}
			tag_value: {type: "string", filterable: true}
			tags: {type: "string", filterable: true}
			tags_string: {type: "string", filterable: true}
			tenant_id: {type: "string", filterable: true}
			updated_at: {type: "string", filterable: true}
			vmware.guest_os_id: {type: "string", filterable: true}
			vmware.guest_os_version: {type: "string", filterable: true}
			vmware.host_system_name: {type: "string", filterable: true}
			vmware.host_type: {type: "string", filterable: true}
			vmware.instance_uuid: {type: "string", filterable: true}
			vmware.vm_host_name: {type: "string", filterable: true}
			vmware.vm_tools_status: {type: "string", filterable: true, enum: ["enabled", "disabled"]}
		}
	}

	oci: {
		fql_properties: {
			compartment_ocid: {type: "string", filterable: true}
		}
	}

	gcp: {
		fql_properties: {
			gcp.multi_region: {type: "string", filterable: true}
			gcp.physical_region: {type: "string", filterable: true}
		}
	}

	aspm_f_g_a: {
		fql_properties: {
			aspm.cloud_account: {type: "string", filterable: true}
			aspm.cloud_region: {type: "string", filterable: true}
			aspm.deployment_provider: {type: "string", filterable: true}
			aspm.deployment_type: {type: "string", filterable: true}
		}
	}

	evaluation: {
		fql_properties: {
			account_bitmap_token_64: {type: "string", filterable: true}
			account_id: {type: "string", filterable: true}
			account_name: {type: "string", filterable: true}
			applicable_profile: {type: "string", filterable: true}
			arn: {type: "string", filterable: true}
			attack_type: {type: "string", filterable: true}
			benchmark_name: {type: "string", filterable: true}
			benchmark_version: {type: "string", filterable: true}
			business_impact: {type: "string", filterable: true}
			cid: {type: "string", filterable: true}
			cloud_group: {type: "string", filterable: true}
			cloud_provider: {type: "string", filterable: true}
			cloud_scope: {type: "string", filterable: true}
			created_at: {type: "string", filterable: true}
			crn: {type: "string", filterable: true}
			data_classification_tag: {type: "string", filterable: true}
			environment: {type: "string", filterable: true}
			extension_status: {type: "string", filterable: true, enum: ["enabled", "disabled"]}
			findings: {type: "string", filterable: true}
			first_detected: {type: "string", filterable: true}
			framework: {type: "string", filterable: true}
			groups: {type: "string", filterable: true}
			id: {type: "string", filterable: true}
			last_detected: {type: "string", filterable: true}
			policy_id: {type: "string", filterable: true}
			policy_name: {type: "string", filterable: true}
			policy_uuid: {type: "string", filterable: true}
			region: {type: "string", filterable: true}
			remediation: {type: "string", filterable: true}
			requirement: {type: "string", filterable: true}
			requirement_name: {type: "string", filterable: true}
			resource_account_id: {type: "string", filterable: true}
			resource_account_name: {type: "string", filterable: true}
			resource_captured: {type: "string", filterable: true}
			resource_cloud_context: {type: "string", filterable: true}
			resource_gcrn: {type: "string", filterable: true}
			resource_id: {type: "string", filterable: true}
			resource_parent: {type: "string", filterable: true}
			resource_region: {type: "string", filterable: true}
			resource_status: {type: "string", filterable: true, enum: ["enabled", "disabled"]}
			resource_type: {type: "string", filterable: true}
			resource_type_name: {type: "string", filterable: true}
			resource_version: {type: "string", filterable: true}
			revision: {type: "string", filterable: true}
			rule_controls: {type: "string", filterable: true}
			rule_description: {type: "string", filterable: true}
			rule_group: {type: "string", filterable: true}
			rule_id: {type: "string", filterable: true}
			rule_identifier: {type: "string", filterable: true}
			rule_name: {type: "string", filterable: true}
			rule_origin: {type: "string", filterable: true, enum: ["Default", "Custom"]}
			rule_policy_id: {type: "string", filterable: true}
			rule_remediation: {type: "string", filterable: true}
			rule_severity: {type: "string", filterable: true, enum: ["Critical", "High", "Medium", "Informational"]}
			rule_threat: {type: "string", filterable: true}
			section: {type: "string", filterable: true}
			service: {type: "string", filterable: true}
			service_category: {type: "string", filterable: true}
			severity: {type: "string", filterable: true}
			status: {type: "string", filterable: true}
			suppressed_by: {type: "string", filterable: true}
			suppression_reason: {type: "string", filterable: true}
			tactic_id: {type: "string", filterable: true}
			tactic_name: {type: "string", filterable: true}
			tag_key: {type: "string", filterable: true}
			tag_value: {type: "string", filterable: true}
			tags: {type: "string", filterable: true}
			tags_string: {type: "string", filterable: true}
			technique_id: {type: "string", filterable: true}
			technique_name: {type: "string", filterable: true}
			tenant_id: {type: "string", filterable: true}
			url: {type: "string", filterable: true}
			version: {type: "string", filterable: true}
			zone: {type: "string", filterable: true}
		}
	}

	azure: {
		fql_properties: {
			azure.resource_group: {type: "string", filterable: true}
			azure.vm_id: {type: "string", filterable: true}
			configuration.id: {type: "string", filterable: true}
		}
	}
}
