// Code generated by fqlmeta. DO NOT EDIT.
// Generated at: 2026-08-21T14:28:14Z

name: "iac"

entities: {
	combined_detections_a_p_i: {
		fql_properties: {
			detection_uuid: {type: "string", filterable: true}
			file_name: {type: "string", filterable: true}
			is_from_module: {type: "string", filterable: true}
			last_detected: {type: "string", filterable: true}
			module_path: {type: "string", filterable: true}
			module_source: {type: "string", filterable: true}
			module_version: {type: "string", filterable: true}
			platform: {type: "string", filterable: true}
			project_name: {type: "string", filterable: true}
			project_owner: {type: "string", filterable: true}
			project_ref: {type: "string", filterable: true}
			provider: {type: "string", filterable: true}
			resource_name: {type: "string", filterable: true}
			rule_category: {type: "string", filterable: true}
			rule_name: {type: "string", filterable: true}
			rule_type: {type: "string", filterable: true}
			rule_uuid: {type: "string", filterable: true}
			service: {type: "string", filterable: true}
			severity: {type: "string", filterable: true}
		}
	}
}
