// Code generated by fqlmeta. DO NOT EDIT.
// Generated at: 2026-08-21T14:24:34Z

name: "policymanagementframework"

entities: {
	rule: {
		fql_properties: {
			policy_name: {type: "string", aggregatable: true}
			policy_uuid: {type: "string", sortable: true, aggregatable: true}
			rule_annotation_status: {type: "string", filterable: true, enum: ["pending_review", "accepted", "rejected", "unaccepted"]}
			rule_auto_remediable: {type: "string", filterable: true, sortable: true, enum: ["true", "false"]}
			rule_category: {type: "string", filterable: true, sortable: true}
			rule_cloneable: {type: "string", filterable: true, sortable: true, enum: ["true", "false"]}
			rule_compliance_benchmark: {type: "string", filterable: true, sortable: true, aggregatable: true}
			rule_compliance_benchmark_uuid: {type: "string", filterable: true, sortable: true}
			rule_compliance_framework: {type: "string", filterable: true, sortable: true, aggregatable: true}
			rule_control_requirement: {type: "string", filterable: true, sortable: true, aggregatable: true}
			rule_control_section: {type: "string", filterable: true, sortable: true, aggregatable: true}
			rule_created_at: {type: "string", filterable: true, sortable: true}
			rule_description: {type: "string", filterable: true, sortable: true}
			rule_domain: {type: "string", filterable: true, sortable: true, enum: ["CSPM", "Runtime"]}
			rule_mitre_tactic: {type: "string", filterable: true, sortable: true, aggregatable: true}
			rule_mitre_technique: {type: "string", filterable: true, sortable: true, aggregatable: true}
			rule_name: {type: "string", filterable: true, sortable: true, aggregatable: true}
			rule_origin: {type: "string", filterable: true, sortable: true, aggregatable: true, enum: ["Default", "Custom"]}
			rule_parent_uuid: {type: "string", filterable: true, sortable: true}
			rule_provider: {type: "string", filterable: true, sortable: true, aggregatable: true, enum: ["General", "AWS", "GCP", "Azure", "OCI", "ASPM"]}
			rule_resource_type: {type: "string", filterable: true, sortable: true, aggregatable: true}
			rule_resource_type_name: {type: "string", filterable: true, sortable: true, aggregatable: true}
			rule_risk_factor: {type: "string", filterable: true}
			rule_service: {type: "string", filterable: true, sortable: true, aggregatable: true}
			rule_severity: {type: "string", filterable: true, sortable: true, aggregatable: true, enum: ["Informational", "Medium", "High", "Critical"]}
			rule_short_code: {type: "string", filterable: true, sortable: true, aggregatable: true}
			rule_status: {type: "string", filterable: true, enum: ["enabled", "disabled"]}
			rule_subdomain: {type: "string", filterable: true, sortable: true, enum: ["IOM", "IAC", "CloudRisk", "Insight", "FCSCloudRisk", "Annotation"]}
			rule_updated_at: {type: "string", filterable: true, sortable: true}
			rule_updated_by: {type: "string", filterable: true, sortable: true}
			rule_uuid: {type: "string", filterable: true, sortable: true, aggregatable: true}
			rulegroup_name: {type: "string", aggregatable: true}
			rulegroup_uuid: {type: "string", sortable: true, aggregatable: true}
		}
	}

	rule_group: {
		fql_properties: {
			policy_name: {type: "string", filterable: true, aggregatable: true}
			policy_uuid: {type: "string", filterable: true, aggregatable: true}
			rule_name: {type: "string", filterable: true, aggregatable: true}
			rule_uuid: {type: "string", filterable: true, aggregatable: true}
			rulegroup_created_at: {type: "string", filterable: true}
			rulegroup_description: {type: "string", filterable: true}
			rulegroup_domain: {type: "string", filterable: true}
			rulegroup_name: {type: "string", filterable: true, aggregatable: true}
			rulegroup_origin: {type: "string", filterable: true, aggregatable: true, enum: ["Default", "Custom"]}
			rulegroup_subdomain: {type: "string", filterable: true, enum: ["IOM", "IAC", "CloudRisk", "Insight", "FCSCloudRisk", "Annotation"]}
			rulegroup_updated_at: {type: "string", filterable: true}
			rulegroup_updated_by: {type: "string", filterable: true}
			rulegroup_uuid: {type: "string", aggregatable: true}
		}
	}

	policy: {
		fql_properties: {
			policy_assignment_target_id: {type: "string", filterable: true, aggregatable: true}
			policy_assignment_target_name: {type: "string", filterable: true, aggregatable: true}
			policy_created_at: {type: "string", filterable: true}
			policy_description: {type: "string", filterable: true}
			policy_domain: {type: "string", filterable: true, enum: ["CSPM", "Runtime"]}
			policy_name: {type: "string", filterable: true, aggregatable: true}
			policy_origin: {type: "string", filterable: true, aggregatable: true, enum: ["Default", "Custom"]}
			policy_status: {type: "string", filterable: true, aggregatable: true, enum: ["enabled", "disabled"]}
			policy_subdomain: {type: "string", filterable: true, enum: ["IOM", "IAC", "CloudRisk", "Insight", "FCSCloudRisk", "Annotation"]}
			policy_updated_at: {type: "string", filterable: true}
			policy_updated_by: {type: "string", filterable: true}
			policy_uuid: {type: "string", aggregatable: true}
			rule_name: {type: "string", aggregatable: true}
			rule_uuid: {type: "string", aggregatable: true}
			rulegroup_name: {type: "string", filterable: true, aggregatable: true}
			rulegroup_uuid: {type: "string", filterable: true, aggregatable: true}
		}
	}

	policy_assignment: {
		fql_properties: {
			policy_assignment_policy_uuid: {type: "string", filterable: true}
			policy_assignment_target_id: {type: "string", filterable: true, aggregatable: true}
			policy_assignment_target_name: {type: "string", filterable: true}
			policy_assignment_target_type: {type: "string", filterable: true, aggregatable: true, enum: ["cspm_aws_account", "cspm_azure_account", "cspm_gcp_account"]}
		}
	}

	rule_override: {
		fql_properties: {
			crn: {type: "string", filterable: true}
			rule_override_policy_uuid: {type: "string", filterable: true}
			rule_override_rule_uuid: {type: "string", filterable: true}
			target_id: {type: "string", filterable: true}
		}
	}

	compliance_control: {
		fql_properties: {
			compliance_control_authority: {type: "string", filterable: true, aggregatable: true, enum: ["APRA", "ASD's ACSC", "Adobe", "Amazon", "BSI", "CCCS", "CIS", "CISA", "CNBV", "CSA", "Custom", "EU", "FedRAMP", "HIPAA", "HITRUST", "ISO", "MPA", "Microsoft", "NCSC", "NIST", "New York State", "OWASP", "PCI", "SCF", "SOC2"]}
			compliance_control_benchmark_name: {type: "string", filterable: true, aggregatable: true}
			compliance_control_benchmark_version: {type: "string", filterable: true, aggregatable: true}
			compliance_control_name: {type: "string", filterable: true, aggregatable: true}
			compliance_control_requirement: {type: "string", filterable: true, aggregatable: true}
			compliance_control_section: {type: "string", filterable: true, aggregatable: true}
			compliance_control_type: {type: "string", filterable: true, aggregatable: true}
		}
	}

	compliance_framework: {
		fql_properties: {
			compliance_framework_authority: {type: "string", filterable: true, aggregatable: true, enum: ["APRA", "ASD's ACSC", "Adobe", "Amazon", "BSI", "CCCS", "CIS", "CISA", "CNBV", "CSA", "Custom", "EU", "FedRAMP", "HIPAA", "HITRUST", "ISO", "MPA", "Microsoft", "NCSC", "NIST", "New York State", "OWASP", "PCI", "SCF", "SOC2"]}
			compliance_framework_name: {type: "string", filterable: true, aggregatable: true}
			compliance_framework_version: {type: "string", filterable: true, aggregatable: true}
		}
	}

	suppression_rule: {
		fql_properties: {
			created_at: {type: "string", filterable: true, sortable: true}
			created_by: {type: "string", filterable: true, sortable: true, aggregatable: true}
			description: {type: "string", filterable: true, sortable: true, aggregatable: true}
			disabled: {type: "string", filterable: true, enum: ["true", "false"]}
			domain: {type: "string", filterable: true, sortable: true, enum: ["CSPM", "Runtime"]}
			groups: {type: "string", filterable: true}
			last_modified_at: {type: "string", filterable: true, sortable: true}
			last_modified_by: {type: "string", aggregatable: true}
			name: {type: "string", filterable: true, sortable: true, aggregatable: true}
			subdomain: {type: "string", filterable: true, sortable: true, enum: ["IOM", "IAC", "CloudRisk", "Insight", "FCSCloudRisk", "Annotation"]}
			suppression_expiration_date: {type: "string", filterable: true, sortable: true}
			suppression_reason: {type: "string", filterable: true, sortable: true, aggregatable: true}
		}
	}
}
